name: Build & Push Docker Images

on:
  push:
    branches: [main]

env:
  BACKEND_IMAGE: vivekrana2012/zault-backend
  FRONTEND_IMAGE: vivekrana2012/zault-frontend

jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: docker/build-push-action@v6
        with:
          context: backend
          push: true
          tags: ${{ env.BACKEND_IMAGE }}:latest

  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - uses: docker/build-push-action@v6
        with:
          context: frontend
          push: true
          tags: ${{ env.FRONTEND_IMAGE }}:latest
